[package]
name = "keyvisor-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "keyvisor"
path = "src/main.rs"

[dependencies]
base64 = "0.22.1"
keyvisor-agent = { path = "../keyvisor-agent" }
keyvisor-core.workspace = true
keyvisor-tpm.workspace = true
rustix = { version = "1.1.4", features = ["process", "termios"] }
sha2 = "0.10.9"
zeroize = "1.8.2"

[lints]
workspace = true
